# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lore < Formula
  desc "A CLI tool that captures the why behind your code, one commit at a time"
  homepage "https://github.com/GreyCoderK/lore"
  version "1.0.0"
  license "AGPL-3.0-or-later"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/GreyCoderK/lore/releases/download/v1.0.0/lore_Darwin_x86_64.tar.gz"
      sha256 "40268d39b37655526ec2af4f5e5f3117481dfe7c0a1cc776e5bbc7cf6ddb1b32"

      define_method(:install) do
        bin.install "lore"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/GreyCoderK/lore/releases/download/v1.0.0/lore_Darwin_arm64.tar.gz"
      sha256 "fa5a1a4da246d922e6784d1b52eee957b7d1a5b4998d23e359408e28270891a0"

      define_method(:install) do
        bin.install "lore"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/GreyCoderK/lore/releases/download/v1.0.0/lore_Linux_x86_64.tar.gz"
      sha256 "887cb187e5609650a1465831f2d8c015df4c37e84fae2e1d64d32d90f360c626"
      define_method(:install) do
        bin.install "lore"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/GreyCoderK/lore/releases/download/v1.0.0/lore_Linux_arm64.tar.gz"
      sha256 "1d9641a2875fe8356ce75730188c42524f6fba71c21786cc75685f6682671d2e"
      define_method(:install) do
        bin.install "lore"
      end
    end
  end

  test do
    system "#{bin}/lore", "--help"
  end
end
