# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lore < Formula
  desc "A CLI tool that captures the why behind your code, one commit at a time"
  homepage "https://github.com/GreyCoderK/lore"
  version "1.0.0"
  license "AGPL-3.0-or-later"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/GreyCoderK/lore/releases/download/v1.0.0/lore_Darwin_x86_64.tar.gz"
      sha256 "de6b66a8260edc533a5bfbbeaec77fd0aeeadb81ba53de906b715895be6b8a30"

      define_method(:install) do
        bin.install "lore"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/GreyCoderK/lore/releases/download/v1.0.0/lore_Darwin_arm64.tar.gz"
      sha256 "c8b6626399350e4a46b0c4b06bb02770de080842dfb5618370cfc07788b50363"

      define_method(:install) do
        bin.install "lore"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/GreyCoderK/lore/releases/download/v1.0.0/lore_Linux_x86_64.tar.gz"
      sha256 "79604b7b6d7d2a9696d331767eed061055cb197e32a9ab056d9d9120dbefd5bf"
      define_method(:install) do
        bin.install "lore"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/GreyCoderK/lore/releases/download/v1.0.0/lore_Linux_arm64.tar.gz"
      sha256 "0cc6c21ef4b6ead6be08f01706a0dddaae9dfe4915036d9520d4efde10322488"
      define_method(:install) do
        bin.install "lore"
      end
    end
  end

  test do
    system "#{bin}/lore", "--help"
  end
end
