# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lore < Formula
  desc "A CLI tool that captures the why behind your code, one commit at a time"
  homepage "https://github.com/GreyCoderK/lore"
  version "1.0.0"
  license "AGPL-3.0-or-later"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/GreyCoderK/lore/releases/download/v1.0.0/lore_Darwin_x86_64.tar.gz"
      sha256 "3fd7f909c865c1a25a23ef4b1853dc39a559084bc3fbdaf70a6ee7580bd7b214"

      define_method(:install) do
        bin.install "lore"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/GreyCoderK/lore/releases/download/v1.0.0/lore_Darwin_arm64.tar.gz"
      sha256 "c3fdc6ad9b5e2f1164a51d6b25959a275cf1c61a008a9add25a2329f77c65b8b"

      define_method(:install) do
        bin.install "lore"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/GreyCoderK/lore/releases/download/v1.0.0/lore_Linux_x86_64.tar.gz"
      sha256 "9d1fb2c0306921831922642cc4f7004a9d2edf2dc06221a4f6b185b003ed6616"
      define_method(:install) do
        bin.install "lore"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/GreyCoderK/lore/releases/download/v1.0.0/lore_Linux_arm64.tar.gz"
      sha256 "5a7d83aeadee869b0ba96597983444a2f846305b9b131e5c3395b2bb16d562b8"
      define_method(:install) do
        bin.install "lore"
      end
    end
  end

  test do
    system "#{bin}/lore", "--help"
  end
end
